### ISSUE TITLE
Interpreter/namespaces not functioning as expected

### ISSUE THREAD

**Issue by saluker** [jonathanslenders/ptpython#156]
My understanding from https://github.com/davidhalter/jedi-vim/issues/498 was that using the Interpreter with namespaces is highly more performant that pure static analysis and should return the same (if not better) results.  I'm getting slower performance and incorrect results using namespaces/Interpreter.  See below:

```python
import jedi
def x():
    return ''  
script = jedi.Interpreter('''
x().startsw''', [locals()])
print 'w/ namespace:',', '.join([c.name for c in script.completions()])

script = jedi.Interpreter('''
def x():
    return ''  
x().startsw''', [])
print 'w/o namespace:',', '.join([c.name for c in script.completions()])
```

Results in:
```
w/ namespace: 
w/o namespace: startswith
```

I'm using it based on the docstring in the Interpreter class.  Any ideas?

**Comment by jonathanslenders** [comment]
Hi @saluker,

In the first case, there is no way for Jedi to know that the result type of the function "x" is a string without executing it. I think it's a conscious decision to not execute callables (like methods) to retrieve their completions, because this could cause side effects. On the other hand, it is possible to know that the result type is a string by parsing the code.

Maybe @davidhalter could explain in better. I guess Jedi stays a best effort implementation of what is possible within the bounds of a language as dynamic as Python.

Jonathan

**Comment by saluker** [comment]
Thanks for that, @jonathanslenders !

I'm confused though how this relates to @davidhalter comments in https://github.com/davidhalter/jedi-vim/issues/498 -- my understanding is he was suggesting that ptpython somehow does execute code and that's why it's so much faster than "purely with text".  I looked at how ptpython uses jedi under the hood and tried to copy it, but ended up with the results above.  I realize now I put this issue in the wrong repo, but could you shed some light on your use of jedi in ptpython and why the decision was made to use Interpreter as opposed to Script (i.e pure text analysis)?  Seems the latter is faster is better, no?

**Comment by jonathanslenders** [comment]
Unfortunately, I don't know much about how Jedi works internally. ``Interpreter`` was the right API to choose according to the Jedi docs, so that's what I did.

My guess is that Jedi does not really execute code, but rather looks into the ``__dict__`` of objects that were created before. (If they have a ``__dict__``.) I think you can do that rather safe.

**Comment by saluker** [comment]
Thanks @jonathanslenders

**Comment by davidhalter** [comment]
@saluker It's actually not as easy as it might look like. (Though probably part of the problems above are fixed in Jedi's master branch).

I don't have time to explain it all here, but essentially some things are easier to understand with static analysis and some are easier with the dir function.

The dir function is very fast and correct in most cases, but evaluating function objects is a bit hard (if you don't have a reference to the actual code in a file). Remember: You have only access to the function object in a shell, not the code itself. This makes it so you will not be able to know evaluate return statements, unless you execute that function (which you never want for obvious reasons).

Static analysis on the other hand can gather more information.

Let me know if this has helped you understand this issue.

**Comment by saluker** [comment]
@davidhalter That was helpful, thanks.  A few hopefully quick questions that should help others:

1. When I have the luxury of choosing how variables and functions are introduced to the Interpreter (text vs namespace as in the example above), what should the be the rule of thumb for making the decision?
2. For my use case evaluating functions is fine (i.e. sandbox environment).  Can JEDI help with enabling this option?  I understand this might not be possible in the current implementation, but I would try an implementation and some tips from you on where to start would help.
3. Further on #2, if for my use case I'm fine with executing functions, this opens the road to telling the user about syntax or other errors.  Any guidance on JEDI ways of implementing this would be much appreciated.

Thanks!
Serge

**Comment by davidhalter** [comment]
1. Well, I think that static analysis is better (except for direct attribute access like `foo.bar`.
2. Executing functions will not be part of the Jedi API. I think that's just wrong. What I would accept is reverse engineering the code object (`func.__code__.co_code`) and getting some knowledge from the bytecode. However that requires a lot of work, probably (and knowledge).
3. You could execute functions and then kind of pass them back to `jedi.evaluate.compiled.create`, but that has multiple limitations. The biggest one being that the return value might not be returned, because of exceptions (which would happen in a LOT of cases like not entering the correct params). Since I don't want this within Jedi, note that there's no API in Jedi, so you're using Python code that is just internal and subject to change (and probably has changed in the latest branch).
