### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by djoker** [jonathanslenders/ptpython#19]
This is not really a issue. I just don't know how to use it with Python 3. How can I use it with ptpython? Thanks in advance

**Comment by jonathanslenders** [comment]
What operating system are you using?

I recommend to always use virtualenv. When you create a virtualenv, you can pass another Python version. (See: http://stackoverflow.com/questions/1534210/use-different-python-version-with-virtualenv )
If you install ptpython inside the virtualenv, it will automatically use the correct Python version.

Otherwise, If you prefer not to user virtualenv, you can do something like: ``python3.3 `which ptpython` `` (You pass the ptpython executabel to the correct Python process.)

I hope this helps.

**Comment by djoker** [comment]
I use Ubuntu and ```python3 `which ptpython` ``` works fine. Thanks!

PS: I will consider use of virtualenv. For now it's just a test. Thanks again!

**Comment by jonathanslenders** [comment]
You are welcome! Have a good day!
