### ISSUE TITLE
ptpython in cygwin

### ISSUE THREAD

**Issue by juanpabloaj** [jonathanslenders/ptpython#21]
when I use ptpython in cygwin I get this symbols `[13;1R` in the prompt

```bash
$ ptpython
In [1]: [13;1R
```

**Comment by jonathanslenders** [comment]
Thanks for reporting!
That looks like a part of the "cursor position response". I think Cygwin somehow sends the preceding escape separately from this sequence. (The actualy CPR is  ``ESC[13;1R``).

It's not an easy one, because not all terminals behave the same, but I think I can find a workaround.

**Comment by juanpabloaj** [comment]
thanks @jonathanslenders ;)

**Comment by jonathanslenders** [comment]
Hi @juanpabloaj,

Sorry to come back this late. I never tested on Cygwin, but this issue was related to something else. (Correct handling of the escape Key through a timeout.) That was fixed a while ago. So, it's possible that ``ptpython`` should now run fine on Cygwin as well.

If you have some time, could you test once again?

Thanks, Jonathan

**Comment by juanpabloaj** [comment]
yes, now work fine, thanks a lot! :smile:
