### ISSUE TITLE
can't get character \ to work

### ISSUE THREAD

**Issue by anderspersson** [jonathanslenders/ptpython#28]
When i press \ nothing happens, 
It works in Python console, in ipython but not for ptpython or ptipython

I use
Python 3.4 (32 bits) om Windows 7

**Comment by jonathanslenders** [comment]
Hi @anderspersson,

Sorry to come back this late. Could you please try again after install the latest version of ``ptpython``? Just do: ``pip install -U ptpython``. It could be that it's solved by this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/35045205fcdb5389d99ef83a716ffdb8e8b4ff03

Thanks,
Jonathan

**Comment by anderspersson** [comment]
Sorry it don't work, and swedish letter åäö don't work they turn upp as strange character with red backgrounds and as before \ don't show att all.

![image](https://cloud.githubusercontent.com/assets/1372776/8021494/1e86fb42-0ca2-11e5-8c2a-3851676610fc.png)

**Comment by mahadi** [comment]
\ also doesn't work for me on my windows machine. Any news on this topic?

**Comment by jonathanslenders** [comment]
Hi @anderspersson and @mahadi,

Could you report me which version of prompt-toolkit and ptpython you have installed. (Run ``pip freeze``.)
Further, what keyboard layout are you using? And what Windows version?

I tried on my Windows 7 laptop, and backslash works without issues.

Cheers,
Jonathan

**Comment by mahadi** [comment]
prompt-toolkit==0.52
ptpython==0.24
German keyboard layout
Windows 7 64-Bit (Microsoft Windows [Version 6.1.7601])

**Comment by selepo** [comment]
I have the same issue, with both pthpython and xonsh (using prompt-toolkit). If I disable prompt-toolkit in xonsh (using pyreadline), backslash works. 

I am guessing this is something with prompt-toolkit and the environment. Would be happy to help out with debugging this issue, but I would need some hint on where to look  / what to test for...

**Comment by jonathanslenders** [comment]
Hi everyone,

Finally, I think I have found it. On a German keyboard, the right alt (alt-gr) has to be pressed in order to generate a backslash.

However in the following code: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/win32_input.py#L195
we say that any key which has been pressed with "alt" will insert an Escape in front. (This is how vt100 terminals work.) alt-x for instance is the same as meta-x or escape followed by x.

Now it happens that there is a key binding for escape-backslash in Emacs: (currently not implemented yet, but already captured.)
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/emacs.py#L287

I suggest that in win32_input.py, we remove ``ev.ControlKeyState & self.RIGHT_ALT_PRESSED`` and only translate the left alt to escape.

Could you try this?

Jonathan

**Comment by selepo** [comment]
Confirmed that it works with both ptpython and xonsh. (Use swedish keyboard, which use alt-gr as modifier for backslash). 

Pull request: https://github.com/jonathanslenders/python-prompt-toolkit/pull/189

**Comment by mahadi** [comment]
Confirmed. Bugfix is working.
