### ISSUE TITLE
Save config from menu

### ISSUE THREAD

**Issue by wldcordeiro** [jonathanslenders/ptpython#48]
It'd be nice if there were a way to do basic configuration from within pt(i)python like if you change to Vi mode, or colorscheme choices and save those options. Additionally what is the option to set the code color scheme? In your example you have the UI option detailed as `repl.use_ui_colorscheme('blue')`

**Comment by jonathanslenders** [comment]
Hi @wldcordeiro,

Thanks for the feature requests. Saving the configuration from a running shell is difficult, because the configuration can be actual code. I'll think about what the best approach will be, but without promises.

The option for setting the code color scheme is ``use_code_colorscheme(...)``.
I updated the example config:
https://github.com/jonathanslenders/ptpython/blob/master/examples/ptpython_config/config.py#L71

Cheers,
Jonathan
