### ISSUE TITLE
Colors are rendered incorrectly

### ISSUE THREAD

**Issue by Cutuchiqueno** [jonathanslenders/ptpython#93]
I modify colos in the config.py so that they match the colors of base16-monokai which I use in all of my environment. However, I noticed that some of the color values are shown differently from the way they are shown for any other (shell) program or even in the same shell outside of ptipython. Thus, it seems to me that color values are modified incorrectly somewhere albeit I don't really know what the reason is.

![colors](https://cloud.githubusercontent.com/assets/306064/12052207/d30844a6-af0c-11e5-9b84-15157e15c782.png)

In this example blue and green show up correctly (folder color in shell - command color  in ptipython; command color in shell - "In [1]" color in ptipython). However, the color in the type signature which looks like light red/pink has the same color value and thus should look the same way as the yellow user/host line in the shell ("cutuchiqueno … sputnik3arch)

The same happens with some other but not all colors.

**Comment by jonathanslenders** [comment]
Hi @Cutuchiqueno,

Could you share the relevant section of the config.py file?
Sometimes it happens that colors are displayed incorrectly when the terminal has been set up to use custom colors. (Especially if colors are chosen from the 16 color palette.)

What terminal and operating system are you using? And does it happen in all terminal applications?

Jonathan

**Comment by Cutuchiqueno** [comment]
The example case from above is defined by: 
            # Signature toolbar.
        Token.Toolbar.Signature:                      'bg:#272822 #f4bf75',
        Token.Toolbar.Signature.CurrentName:          'bg:#272822 #fd971f bold',
        Token.Toolbar.Signature.Operator:             '#a1efe4 bold',

The color value I was talking about is `#f4bf75`

There are some other colors from the theme which work particualarly bad, mostly grayish color values (from .Xresources):

    ! Grau 1
    #define base01 #383830
    ! Grau 2
    #define base02 #49483e
    ! Beige 1
    #define base03 #75715e
    ! Beige 2
    #define base04 #a59f85

I am on Arch Linux with zsh in termite.

**Comment by jonathanslenders** [comment]
This is weird. Thanks a lot for submitting this issue, but I still don't have any idea what's going on.
It's the `Terminal256Formatter` from Pygments that we use to generate color codes.

It happens on this line: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/vt100_output.py#L121

**Comment by Cutuchiqueno** [comment]
Thanks much for communicating on this issue.

I now made a weired experience which shows that every color is kind of modified in a certain probably the same way. It's just that you see it more with some colors than with others. The color0 for base16-monokai is `#272822`. It's the background color which you see in the screenshot. When I use `#272822` for some color in ´config.py` this should make the Token invisible because it has the same color as the background. However, it's becoming even darker than the background. When I set this token to `#000000´ THEN it is rendered like the background which means rendered like `#272822`. I think during the generation process every color modified incorrectly in the same way not jus some.

For the purpose to exclude some config issues in my environment as much as possible I now also tried it with xterm + bash. The result is the same.

**Comment by jonathanslenders** [comment]
This sounds like a bug. I will try to find some time to reproduce and fix it. Thanks for the info!

**Comment by Cutuchiqueno** [comment]
Thx, for getting on this. In case you need more help from me please tell me.

By the way, this also happens with the syntax highlighting and the monokai theme provided by pygments: `repl.use_code_colorscheme('monokai')`

**Comment by jonathanslenders** [comment]
Hi @Cutuchiqueno,

Could it be that this is caused because we use the 256 color palette. Currently, we use the ``Terminal256Formatter`` from Pygments. (https://bitbucket.org/birkenfeld/pygments-main/src/cb583a0e37c776b77e3c49200c1658c920e9845a/pygments/formatters/terminal256.py?at=default&fileviewer=file-view-default#terminal256.py-82). This means that if a color does not exist on that palette, we will look for the closed matching color.

We could use true colors (24bit), but the difficulties are that not all terminals support that, and secondly, it will need more memory. If I figure out a good way to tell the renderer which color palette he needs to use, I could probably support true colors.

Jonathan

**Comment by jonathanslenders** [comment]
I added support for 24bit full color to prompt_toolkit and ptpython. I hope this works for you.

https://github.com/jonathanslenders/python-prompt-toolkit/commit/70855c996d66a196339b129520eff8c1200c2bec

https://github.com/jonathanslenders/ptpython/commit/94f6c9c48c9189177d50ba785faba9b6ca389d32

By default, 24bit colors are disabled. You can enable it from the menu. (Press CtrL after changing, in order to redraw everything.) Or change it from the configuration file.
https://github.com/jonathanslenders/ptpython/blob/94f6c9c48c9189177d50ba785faba9b6ca389d32/examples/ptpython_config/config.py#L100

Jonathan

**Comment by Cutuchiqueno** [comment]
Dear Jonathan,

thank you very much for this. It's true that it relates to the 24bit support. With this support activated the user interface is rendered correctly. What is strange however (or I am too stupid to understand the context) is the fact that it changes the behavior of the monokai theme provided by pygments. As hallI mentioned before I use the setting `repl.use_code_colorscheme('monokai')`. Thing is that the colors (which should be the same as the once I use for the user interface) are not only rendered in the same way as it was rendered without 24bit support (thus, mostly incorrectly) but that colors also match differently. For instance functions which were blue before are no white. Blue, Green and Red which are used when an error message is dropped are now incorrectly rendered but before they were rendered correctly.

Anyhow, I am really greatful, and maybe it's just changing some more options I was not aware about.
