### ISSUE TITLE
Can we have tab command completion ?

### ISSUE THREAD

**Issue by lowks** [jonathanslenders/ptpython#95]
Can we have tab command completion ? Really miss this coming from `ipython`

**Comment by kernc** [comment]
:+1:

**Comment by jonathanslenders** [comment]
Hi @lowks and @kernc,

What exactly do you mean? Ptpython and ptipython have tab completion. Are you looking for a specific feature? (Could you give an example?)

Thanks,
Jonathan

**Comment by lowks** [comment]
Oh you are right, it's there it was just slow loading up.


[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
  <http://about.me/lowkianseong>

On Sat, Jan 16, 2016 at 8:16 AM, Jonathan Slenders <notifications@github.com

**Comment by kernc** [comment]
Embarrassingly, I don't remember what I meant. It works fine here too. :smile:

**Comment by jonathanslenders** [comment]
No problem!
It could be that Jedi (for the autocompletion) had some delay. The autocompletion works anynchronous, because it involves analysing many Python files. Normally however, it should respond almost immediately.

I'll close this one, but don't hesitate to open a new issue if you encounter an issue!

Cheers,
Jonathan
